spring:
  application:
    name: course

  datasource:
    url: jdbc:postgresql://localhost:5432/course_db
    username: postgres
    password: 1237890zx

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true

    properties:
      hibernate:
        format_sql: true


minio:
  url: http://localhost:9000
  username: admin
  password: admin123


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security:
          config: DEBUG
        context:
          annotation: DEBUG


token:
  signing:
    key: basebasebasebasebasebasebasebasebasebasebasebasebasebasebasebase


log4j:
  appender:
    FILE:
      encoding: UTF-8